name: Test
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build on Debian 11 Python 3.11.4
    steps:
      - uses: actions/checkout@master
      - uses: DDS-Derek/run-on-arch-action@master
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: python
          githubToken: ${{ github.token }}
          run: |
            echo ::set-output name=uname::$(uname -a)
            echo ::set-output name=python3::$(python3 --version)
            echo ::set-output name=pip::$(pip --version)

      - name: Get the output
        run: |
          echo "The uname output was ${{ steps.runcmd.outputs.uname }}"
          echo "The uname output was ${{ steps.runcmd.outputs.python3 }}"
          echo "The uname output was ${{ steps.runcmd.outputs.pip }}"
